name: Continuous Integration for Esteban Ramirez

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Pruebas de SAST mockeadas
    - name: Pruebas de SAST
      run: echo "Ejecución de pruebas de SAST"

    # Paso 3: Creación del archivo de credenciales
    - name: Crear archivo de credenciales
      run: |
        echo "[credentials]" > credentials.ini
        echo "username=esteban" >> credentials.ini
        echo "password=mySecretPassword" >> credentials.ini

    # Paso 4: Construcción de la imagen de Docker
    - name: Build docker image
      run: docker build -t devops_ws . --tag devops_ws_:$(date +%s)
